- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaFieldQuery.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AbstractAvroSchemaRegistryCientTest.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
Updated many schema creation relation unit tests. Also fixed an error where schema description was not returned in get schema API call.
> Add schema creation related unit tests

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/styles/css/theme.css
This PR is to fix: https://hwxiot.atlassian.net/browse/STREAMLINE-634
cc: @harshach
> UI: Not able to copy the schema text

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaInfoForm.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
Addressed comments by @satishd mentioned in https://hwxiot.atlassian.net/browse/STREAMLINE-496
cc: @harshach
> Minor ui feedbacks

- bootstrap/bootstrap-storage.sh
- storage/tool/pom.xml
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/MySqlDriverHelper.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/SQLScriptRunner.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/StorageProviderConfiguration.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/StorageProviderConfigurationReader.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/TablesInitializer.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/Utils.java
- Pulled in changes done in streamline for similar changes.
- Updated with respective registry changes.
> Update script utils for storage providers

- common-auth/src/main/java/com/hortonworks/registries/auth/util/KerberosName.java
- common-auth/src/test/java/com/hortonworks/registries/auth/server/TestKerberosAuthenticationHandler.java
- common-auth/src/test/java/com/hortonworks/registries/auth/util/TestKerberosName.java
> REGISTRY-28: Make SPNEGO work with cross realm kerberos setup

- common-auth/pom.xml
- pom.xml
Build times with this PR (reduced from 16 mins to ~ 5mins). This PR removes src-generation in normal dev(default) maven profile which was taking around 10 mins.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Registry ........................................... SUCCESS [  0.650 s]
[INFO] registry-common .................................... SUCCESS [ 17.732 s]
[INFO] cache .............................................. SUCCESS [  4.730 s]
[INFO] storage ............................................ SUCCESS [  0.011 s]
[INFO] storage-core ....................................... SUCCESS [  6.897 s]
[INFO] storage-tool ....................................... SUCCESS [  3.119 s]
[INFO] schema-registry …
```
> ISSUE-84: Enable source jar generation only for relevant maven profiles

- bootstrap/sql/mysql/create_tables.sql
- bootstrap/sql/postgresql/create_tables.sql
- examples/schema-registry/avro/src/main/java/com/hortonworks/registries/schemaregistry/examples/avro/SampleSchemaRegistryClientApp.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/ISchemaRegistryClient.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SerDesInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SerDesPair.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SerDesInfoStorable.java
- schema-registry/core/src/main/resources/mysql/create_schemaregistry-tables.sql
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
- upload ser/des jar 
- register serdes info 
- map serdes with a schema
Detailed documentation with json structure can be seen with swagger.
> ISSUE-102: Simplify APIs for registering/fetching serdes api.

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/AggregatedSchemaMetadataInfo.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryTest.java
Respective REST APIs are added below.
- GET api/v1/schemaregistry/schemas/aggregated
- GET api/v1/schemaregistry/schemas/{name}/aggregated
Closes #117
> ISSUE-117 Added aggregate APIs for schema metadata

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
> ISSUE-121: Returning right serdes result id

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaInfoForm.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/rest/SchemaREST.js
Fix for https://github.com/hortonworks/registry/issues/107
> Search schema UI integration with search API

- pom.xml
> ISSUE-109: Upgraded avro version to 1.8.2

- examples/schema-registry/serdes/src/main/java/org/apache/schemaregistry/samples/serdes/SimpleDeserializer.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/MySqlDriverHelper.java
- webservice/src/main/java/com/hortonworks/registries/webservice/RegistryApplication.java
- webservice/src/main/java/com/hortonworks/registries/webservice/RegistryConfiguration.java
This is a very minor change. Just remove all unused imports.
_First commit to hortonworks/registry. It's a start._ :smiley:
> ISSUE-151: Remove unused imports

- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentProtocolCompatibleTest.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentRegistryCompatibleResourceTest.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/SerDesProtocolHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSerDesProtocolHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotSerializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AvroSerDesHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AvroSnapshotDeserializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AvroSnapshotSerializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/ConfluentAvroSerDesHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/ConfluentProtocolHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/SchemaMetadataIdProtocolHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/SchemaVersionIdAsLongProtocolHandler.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/SerDesProtocolHandlerRegistry.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/serdes/MessageContextBasedAvroSerializer.java
Add Confluent Wire Protocol support
Copy in handling support for future Kafka Connect Converter support (is supported natively in confluent serdes, but move this so it can be used by any handler)
> ISSUE-126: Add Confluent Compatibility Wire Protocol support

- docs/confluent.rst
Initial work for addending migration documentation.
> ISSUE-120: Add documentation for migration

- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/kafka/KafkaAvroSerde.java
Added Kafka Avro Serde which is needed for Kafka Streams API, etc.
> Kafka Avro Serdes

- examples/schema-registry/avro/src/main/java/com/hortonworks/registries/schemaregistry/examples/avro/KafkaAvroSerDesApp.java
- examples/schema-registry/avro/src/main/resources/kafka-producer.props
> ISSUE-167 Add an option to ignore invalid messages while sending messages to a topic in KafkaAvroSerDesApp

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/ISchemaRegistryClient.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/AggregatedSchemaMetadataInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/CompatibilityResult.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistryService.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadata.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/errors/UnsupportedSchemaTypeException.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/ConfluentSchemaRegistryCompatibleResource.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryTest.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/client/MockSchemaRegistryClient.java
- Align server/client side apis with service api.    
- Aligned without breaking the existing client APIs.
> ISSUE-130 Align server/client side apis with service api.

- common/src/main/java/com/hortonworks/registries/common/Schema.java
Registry changes for https://github.com/hortonworks/streamline/issues/765
> Add BLOB type to schema (Streamline issue 765)

- conf/registry-dev.yaml
- conf/registry.yaml
- conf/registry.yaml.inmemory.example
- examples/schema-registry/avro/src/test/resources/schema-registry-test.yaml
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/ConfluentSchemaRegistryCompatibleResource.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/RewriteUriFilter.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/rest-service/src/test/resources/schema-registry-test-ha.yaml
- schema-registry/rest-service/src/test/resources/schema-registry-test.yaml
- webservice/src/main/java/com/hortonworks/registries/webservice/RegistryApplication.java
- webservice/src/main/resources/app/scripts/components/Header.jsx
- webservice/src/main/resources/app/scripts/components/NoData.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
- webservice/src/main/resources/app/styles/css/theme.css
- webservice/src/main/resources/index.html
- webservice/src/main/resources/public/assets/index.html
- Support forward/redirect filters
- Added respective config to forward Confluent related URIs
- UI bundle is deployed at /ui and / is redirected to /ui
> ISSUE-196 Support forward/redirect filters

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaValidator.java
Minor change: fixed class name & removed unused imports.
> ISSUE-200: Fixed wrong Logger class name in AvroSchemaValidator

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/serde/AbstractSnapshotDeserializer.java
Change code to treat config property as seconds instead of milliseconds
> ISSUE-208: DESERIALIZER_SCHEMA_CACHE_EXPIRY_IN_SECS wrong time unit

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/ConfluentSchemaRegistryCompatibleResource.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentRegistryCompatibleResourceTest.java
- Added more APIs for Confluent SR.
- Fixed returning version id instead of metadata id.
- Added tests for APIs including a stress test.
Tested and verified with MySql storage.
> ISSUE-211 Adding missing APIs for Confluent SR and a fix in returning right id for version.

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/serde/AbstractSerDes.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/serde/AbstractSnapshotDeserializer.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/serde/AbstractSnapshotSerializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializer.java
- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotSerializer.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/serdes/AvroSerDesInitClosureTest.java
> ISSUE-182 Added checks for initialization/closures serializer/deserializer

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
> ISSUE-205 UI not able to display the right schema version number after deletion

- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/ConfluentSchemaRegistryCompatibleResource.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentRegistryCompatibleResourceTest.java
- Return respective error messages for different subject and version not found cases. 
- Added respective tests.
> ISSUE-224 Return respective error messages for different subject and version not found cases.

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionDiff.jsx
- webservice/src/main/resources/app/scripts/libs/jsdifflib/difflib.js
- webservice/src/main/resources/app/scripts/libs/jsdifflib/diffview.css
- webservice/src/main/resources/app/scripts/libs/jsdifflib/diffview.js
- webservice/src/main/resources/app/scripts/main.js
- webservice/src/main/resources/app/styles/css/style.css
> Issue-220-UI Schema Version Diff UI

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaInfoForm.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/rest/SchemaREST.js
- webservice/src/main/resources/app/scripts/utils/Utils.js
- webservice/src/main/resources/app/styles/css/style.css
UI Implementation for schema version state change.
> ISSUE-242 State change implementation

- bootstrap/sql/mysql/create_tables.sql
- bootstrap/sql/mysql/drop_tables.sql
- bootstrap/sql/oracle/create_tables.sql
- bootstrap/sql/oracle/drop_tables.sql
- bootstrap/sql/postgresql/create_tables.sql
- bootstrap/sql/postgresql/drop_tables.sql
- conf/registry.yaml.oracle.example
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/StorageProviderConfiguration.java
Make all schema migration scripts idempotent
> Make all schema migration scripts idempotent

- examples/schema-registry/avro/src/main/java/com/hortonworks/registries/schemaregistry/examples/avro/SampleSchemaRegistryClientApp.java
- registry-dist/VERSION
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/ClassLoaderCache.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/JdbcStorageManager.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/oracle/factory/OracleExecutor.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/sql/factory/AbstractQueryExecutor.java
- Fixed connection leaks in storage layer
- Removed taking file lock as that is not really required as guava cache makes sure to load without contention.
> ISSUE-315 Fix connection leaks in storage layer

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroFieldsGenerator.java
- schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroNestedCheckerTest.java
- schema-registry/common/src/test/resources/avro/nested/nested-complex.avsc
- schema-registry/common/src/test/resources/avro/nested/nested-simple.avsc
Added test resources for testing nested schemas.
Added tests to make sure AvroFieldsGenerator and AvroSchemaProvider can parse nested schemas.
Added code to AvroFieldsGenerator to handle parsing nested schemas.
> ISSUE-410 AvroFieldsGenerator produces Stackoverflow error when parsing a nested record schema.

- webservice/src/main/resources/app/scripts/components/SchemaDetail.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaInfoForm.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
> ISSUE-415: Client side schema validation - Disable or Customize

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
> ISSUE-433: SR home page just spins with some errors on debugger console

- registry-dist/src/main/assembly/binary.xml
> ISSUE-461 Added license and notice files into binary distribution.

- pom.xml
- ISSUE-492 Updated spring-context to 5.0.7.RELEASE to resolve security vulnerabilities
- CVE-2018-11039 and CVE-2018-11040
> ISSUE-492 Updated spring-context to 5.0.7.RELEASE to resolve security vulnerabilities

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
- schema-registry/client/src/test/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClientTest.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistryService.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionLifecycleManager.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/client/MockSchemaRegistryClient.java
- webservice/src/main/resources/app/scripts/components/FSModal.jsx
- webservice/src/main/resources/app/scripts/components/SchemaDetail.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
- webservice/src/main/resources/app/scripts/rest/SchemaREST.js
- webservice/src/main/resources/app/styles/css/style.css
> Expose an option to the user to disable canonical check

- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/oracle/query/OracleSequenceIdQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/sql/factory/AbstractQueryExecutor.java
> ISSUE 560 : Cursor leaks while using Schema Registry against Oracle

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
> ISSUE 574 : Fix the issue while re-creating a deleted schema

- bootstrap/sql/mysql/v006__add_schema_lock_for_existing_schemas.sql
- bootstrap/sql/oracle/v007__add_schema_lock_for_existing_schemas.sql
- bootstrap/sql/postgresql/v006__add_schema_lock_for_existing_schemas.sql
> ISSUE 575 : Add migration to enable editing of schema post upgrade to 0.7

- .travis.yml
> ISSUE 582 : Using OpenJDK intstead of OracleJDK for Travis builds

- common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosBasicAuthenticationHandler.java
NPE in the absence of the Authentication header and when debug is enabled.
> MINOR : NPE when logging is enabled to debug mode

- common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosBasicAuthenticationHandler.java
- common-auth/src/test/java/com/hortonworks/registries/auth/server/TestKerberosBasicAuthenticationHandler.java
> ISSUE-586: KerberosBasicAuthenticationHandler should validate Authorization before processing

- pom.xml
> ISSUE 590 : Update release-sign-artifacts maven profile to generate javadocs and sources

- webservice/src/main/resources/app/scripts/components/SchemaDetail.jsx
> ISSUE 607 : Schema Registry UI hangs occasionally on first use

- examples/schema-registry/avro/pom.xml
- pom.xml
* Apache Common BeanUtils upgraded to v1.9.4.
* Jackson upgraded to v2.10.1.
* Logback upgraded to v1.2.3.
Fixes #627
> ISSUE-627: Remediate Security Vulnerabilities.

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
> ISSUE-653 : Fix NPE while deleting schema metadata with no schema versions

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaInfoForm.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaRegistryContainer.jsx
- webservice/src/main/resources/app/scripts/rest/SchemaREST.js
> ISSUE-656: Delete schema metadata when invalid schema is added

- examples/schema-registry/avro/pom.xml
- pom.xml
* Apache Common BeanUtils upgraded to v1.9.4.
* Jackson upgraded to v2.10.1.
* Logback upgraded to v1.2.3.
> ISSUE-627: Remediate Security Vulnerabilites. (#628)

- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
> ISSUE-661: SchemaRegistry file upload endpoint does not return a json

- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
> ISSUE-670: UI gives exception and blocks when adding incorrect schema

- pom.xml
- Fixed httpclient version according to @risdenk 's recommendation.
- Testing: tested jar upload to Azure Abfs with the new httpclient version.
> CSP-825 Fix HttpClient version for connecting IdBroker

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/cache/SchemaBranchCache.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/cache/SchemaVersionInfoCache.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionLifecycleManager.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- webservice/src/main/java/com/hortonworks/registries/webservice/RegistryApplication.java
In order to support Schema Registry HA, disabled caching on the server side.
> CSP-823 : Disable caching on server side

- schema-registry/authorizer/ranger-plugin/ranger-authorizer/src/main/java/com/hortonworks/registries/schemaregistry/authorizer/ranger/RangerSchemaRegistryAuthorizerImpl.java
- schema-registry/authorizer/ranger-plugin/ranger-authorizer/src/test/java/com/hortonworks/registries/schemaregistry/authorizer/ranger/RangerSchemaRegistryAuthorizerImplTest.java
- schema-registry/authorizer/ranger-plugin/ranger-authorizer/src/test/resources/schema-registry-policies.json
> ISSUE-685: Updates related to removing of none-sb and none-sv resources

- common-auth/pom.xml
- common/pom.xml
- common/src/main/java/com/hortonworks/registries/common/util/FileStorage.java
- common/src/main/java/com/hortonworks/registries/common/util/HdfsFileStorage.java
- common/src/test/java/com/hortonworks/registries/common/util/AbstractFileStorageTest.java
- common/src/test/java/com/hortonworks/registries/common/util/HdfsFileStorageTest.java
- common/src/test/java/com/hortonworks/registries/common/util/HfsFileStorageKerberosTest.java
- common/src/test/java/com/hortonworks/registries/common/util/LocalFileSystemStorageTest.java
- common/src/test/java/com/hortonworks/registries/common/util/MockFileSystem.java
- pom.xml
- schema-registry/rest-service/pom.xml
This is a cherry pick of https://github.com/hortonworks/registry/pull/669 with **hadoop dependencies** changed from **internal** ones to **Apache** ones.
> CSP-825 Schema Registry Kerberized HDFS and Cloud Storage Support

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/BasicSchemaRegistryClientOpsTest.java
>   ISSUE-680 : getLatestSchemaVersion should return the latest enabled schema

- pom.xml
> ISSUE-692: Upgrade Jetty to 9.4.26.v20200117

- pom.xml
> ISSUE-705: Revert the Jetty version overrides

- pom.xml
- webservice/pom.xml
> ISSUE-707: Upgrade to Dropwizard 1.3.22

- cache/pom.xml
Change-Id: If9c8b2673979ed952d07551b5a0cf3e69d0c30dc
Fixes #714
> ISSUE-714: Upgrade netty to 4.0.56

- pom.xml
Change-Id: Id59a11bf737fc309b6bb892cd2de9b901a241967
Fixes #716
> ISSUE-716: Upgrade springframework to 5.0.16

- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializer.java
Fixed reading boolean value of specific.avro.reader
> ISSUE-648: Fixed reading boolean value of specific.avro.reader

- build.gradle
- dependencies.gradle
- gradle.properties
- registry-common-client/build.gradle
[Dependencies after the upgrade](https://github.com/hortonworks/registry/files/9745397/deps.txt)
> ISSUE-763: Upgrade Dropwizard to v2.1.2
