hortonworks/registry

- pom.xml
This version (0.1.0-SNAPSHOT) builds fine.  I've been using this modification for crossbuilding our 2.11 Scala applications.
> Removed declared dependency on 2.10.x Scala so it's possible to crossbuild 2.11 Scala apps via SBT.

- bootstrap/sql/mysql/drop_tables.sql
[drop_schemaregistry-tables.sql](https://github.com/hortonworks/registry/blob/master/schema-registry/core/src/main/resources/mysql/drop_schemaregistry-tables.sql) contains the script but [drop_tables.sql](https://github.com/hortonworks/registry/blob/master/bootstrap/sql/mysql/drop_tables.sql) is missing the same.
> ISSUE#43 drop tables script is missing in the script

- docker/images/registry/Dockerfile
- docker/pom.xml
- pom.xml
Initial support for building Docker images via Maven. The image can be
built as part of the build process by using the Maven Profile
“-Pdocker” and does expect that “registry-dist” has been previously
built. The easiest way to ensure this is always including “-Pdist” with
the Maven command as well.
> registry-docker

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/SingletonInmemoryStore.java
- storage/core/src/main/java/com/hortonworks/registries/storage/CacheBackedStorageManager.java
- storage/core/src/main/java/com/hortonworks/registries/storage/OrderByField.java
- storage/core/src/main/java/com/hortonworks/registries/storage/StorageManager.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/JdbcStorageManager.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/mysql/factory/MySqlExecutor.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/mysql/query/MySqlSelectQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/phoenix/factory/PhoenixExecutor.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/phoenix/query/PhoenixSelectQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/postgresql/factory/PostgresqlExecutor.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/postgresql/query/PostgresqlSelectQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/sql/factory/QueryExecutor.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/sql/query/AbstractSelectQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/memory/InMemoryStorageManager.java
- storage/core/src/test/java/com/hortonworks/registries/storage/AbstractStoreManagerTest.java
- storage/core/src/test/java/com/hortonworks/registries/storage/impl/jdbc/mysql/MySqlSelectQueryTest.java
- storage/core/src/test/java/com/hortonworks/registries/storage/impl/jdbc/postgres/PostgresSelectQueryTest.java
- storage/core/src/test/java/com/hortonworks/registries/storage/impl/memory/InmemoryManagerTest.java
- orderByField query parsing is pushed to the service instead of keeping at JDBC storage manager level. 
- Added new API in `StorageManager` for order by fields.
> ISSUE-80: _orderByField should have been handled for inmemory storage manager

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/ClassLoaderCache.java
- logging an error message instead of throwing an error in race conditions
> Ensuring local-jars directory is created only when it is really needed

- docs/install.rst
1. Rename the db name from `registry_db` to `schema_registry`, because the `registry.yaml`  uses `schema_registry` as the default db name. Or new users will get error.
2. The step "Run bootstrap scripts" for CentOS/RetHat is missing.
3. Also added "Download latest Schema Registry binaries" step for CentOS/RetHat.
> ISSUE-159: Fix the install document

- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/kafka/KafkaAvroSerde.java
Added Kafka Avro Serde which is needed for Kafka Streams API, etc.
This is a PR for squashed version of PR 64.
> Kafka Avro Serdes

- .travis.yml
- dev-tools/travis/print-errors-from-test-reports.py
- dev-tools/travis/ratprint.py
- dev-tools/travis/save-logs.py
- dev-tools/travis/travis-install.sh
- dev-tools/travis/travis-script.sh
* script codes are borrowed from Apache Storm (license block is kept)
I guess we didn't check RAT, but at some time we may want to check RAT (regardless of HWX license header or Apache license header or whatever) so I'm leaving RAT related script.
Unlike storm-core, the output of unit tests is not suppressed. But current output log file is 2M and limit for Travis CI is 10M which makes me feel safe.
I'm also open to integrate with other CI services. Just would like to ensure each PR can be verified.
(I meant it doesn't break the build and unit tests are successful.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hortonworks/registry/187)
> Integrate Travis CI build

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/AggregatedSchemaMetadataInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/CompatibilityResult.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/ConfigEntry.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaFieldInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaIdVersion.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadata.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersion.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionKey.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SerDesInfo.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SerDesPair.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryClientTest.java
- storage/core/src/main/java/com/hortonworks/registries/storage/search/OrderBy.java
- storage/core/src/main/java/com/hortonworks/registries/storage/search/Predicate.java
- storage/core/src/main/java/com/hortonworks/registries/storage/search/PredicateCombinerPair.java
- storage/core/src/main/java/com/hortonworks/registries/storage/search/SearchQuery.java
- storage/core/src/main/java/com/hortonworks/registries/storage/search/WhereClause.java
This allows schema registry clients with earlier versions to send old POJOs to new versions of SchemaRegistry server and deserialization will not look for missing fields in respective POJOs SchemaRegsitry server.
> ISSUE-213 POJOs are made to be backward compatible

- bootstrap/sql/postgresql/v002__create_schema_version_state.sql
This resolves issue #241 by making the details column nullable for postgres.
> Aligning the schema_version_state ddl between postgres and mysql

- DEVELOPER.md
- dev-tools/merge_registry_pr.py
* introduce merge script which is based on Spark merge script and borrow some block from Kafka
* removed unnecessary parts regarding porting back, handling JIRA issues including marking versions
This closes #263 but need to remove CHANGELOG.md separately since including removal of CHANGELOG.md will incur merge conflict.
Please play with merge script to determine how it works and how it configures commit title and commit message of squashed commit.
The script is not that complicated if you are familiar with git command so you may want to also read the script.
Please note that PR's body is picked for squashed commit message instead of accumulation of commit messages in PR's commits. This is based on the decision that Spark / Kafka / etc projects define the template of pull request which …
> ISSUE-263 Improve the commit process

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroFieldsGenerator.java
- schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroNestedCheckerTest.java
- schema-registry/common/src/test/resources/avro/nested/nested-complex.avsc
- schema-registry/common/src/test/resources/avro/nested/nested-simple.avsc
Added test resources for testing nested schemas.
Added tests to make sure AvroFieldsGenerator and AvroSchemaProvider can parse nested schemas.
Added code to AvroFieldsGenerator to handle parsing nested schemas.
I'd like to fix this against v0.3.1, since we're looking at using the Hortonworks Schema Registry with NiFi, and as of this PR submission, NiFi 1.5 is compatible with v0.3.0, and it seems there was API changes in v0.4+
> ISSUE-410 (v0.3.1) AvroFieldsGenerator produces Stackoverflow error when parsing a nested record schema.

- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/initenv/mysql/MySqlDatabaseCreator.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/initenv/mysql/MySqlUserCreator.java
Manually tested from both MySQL 5.7 in MacOS and MySQL 5.6 in Linux.
This closes #428
> ISSUE-428 Lowercase mysql table names in storage initenv

- common-auth/pom.xml
apacheds-jdbm1-2.0.0-M2.bundle is no longer available on nexus so the build will fail.   This fix will download the correct artifact apacheds-jdbm1-2.0.0-M2.jar from nexus.
> fix download of apacheds-jdbm1 jar instead of bundle

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroFieldsGenerator.java
- schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroNestedCheckerTest.java
- schema-registry/common/src/test/resources/avro/nested/nested-complex.avsc
- schema-registry/common/src/test/resources/avro/nested/nested-simple.avsc
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionLifecycleManager.java
- storage/core/src/main/java/com/hortonworks/registries/storage/impl/jdbc/provider/oracle/query/OracleUpdateQuery.java
Fix ORA-01461 (https://support.oracle.com/knowledge/Middleware/1620109_1.html) when using the "merge" command which is used in addOrUpdate as part of storage layer. We hit this bug when we use addOrUpdate for updating schemaVersionStorable's state after persisting schemaStateStorable. Here we can use update instead of addOrUpdate as it serves the same purpose and help to circumvent the JDBC bug.
> HOTFIX : Work around JDBC bug (ORA-01461) while inserting a schema text larger than 4k characters

- pom.xml
- schema-registry/serdes/pom.xml
CVE-2018-14719
CVE-2018-14720
CVE-2018-14721
CVE-2018-1000873
CVE-2018-7489
CVE-2018-19362
CVE-2017-15095
CVE-2018-19361
CVE-2017-7525
CVE-2018-19360
CVE-2017-17485
CVE-2018-5968
> MINOR: Upgrade jackson-databind to v2.9.8 to fix the below CVEs.

- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
- schema-registry/client/src/test/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClientTest.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistryService.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionLifecycleManager.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/client/MockSchemaRegistryClient.java
- webservice/src/main/resources/app/scripts/components/FSModal.jsx
- webservice/src/main/resources/app/scripts/components/SchemaDetail.jsx
- webservice/src/main/resources/app/scripts/containers/Registry-Services/SchemaRegistry/SchemaVersionForm.jsx
- webservice/src/main/resources/app/scripts/rest/SchemaREST.js
- webservice/src/main/resources/app/styles/css/style.css
> ISSUE 555 : Expose an option to disable canonical check while adding a new schema version

- common-auth/src/main/java/com/hortonworks/registries/auth/AbstractLogin.java
- common-auth/src/main/java/com/hortonworks/registries/auth/KerberosLogin.java
- common-auth/src/main/java/com/hortonworks/registries/auth/Login.java
- common-auth/src/main/java/com/hortonworks/registries/auth/NOOPLogin.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
> ISSUE 568 : Synchronize Kerberos ticket renewal for non-renewable ticket

- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/ISchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaVersionLifecycleManager.java
- schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java
- schema-registry/serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaRegistryTest.java
Adds a new REST endpoint to find a schema version by the fingerprint of
the schema text.
> Issue 578: Find schema version by fingerprint of schema text.

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaBranchKey.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaProvider.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaResolver.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaValidator.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaBranchStorable.java
Preparing for the upcoming release of Avro 1.9.0,
there are some methods and transitive dependencies
that have been removed.
Resolves #548 
~~This still needs some work regarding default values.
As of 1.8.x, Avro's Schema.Field class exposed
'defaultValue', returning a JsonNode. That method is
package private in 1.9.0-SNAPSHOT, in favor of defaultVal
returning an Object. In this instance, we have no way to
distinguish between 'null' as a default and a field having
no default at all.
So we need to figure out how to manage
these cases. We could try to squeeze in 'hasDefault' before
the new Avro release but we will be binary incompatible at
that point so we would need 2 registry builds for Avro 1.8.x
and 1.9.0.~~
Mostly false alarm on the above comment. I spent a bunch of time
setting up …
> ISSUE-548: Make compatible with Avro 1.9.0

- bin/registry-server-start.sh
- common/pom.xml
- examples/schema-registry/avro/src/main/resources/yelp_review.avsc
- pom.xml
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/DatabaseUserInitializer.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/MySqlDriverHelper.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/SchemaFlywayFactory.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/TablesInitializer.java
- storage/tool/src/main/java/com/hortonworks/registries/storage/tool/sql/Utils.java
* Used G1GC instead of parallel GC.
* Included JAXB-API and it's runtime jars to run the JDK8 compiled build on JRE11.
> ISSUE-598: Fix SR to run on Java 11

- common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosAuthenticationHandler.java
> ISSUE-603: Minor: Registry is failing to parse the doAs user

- pom.xml
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentProtocolCompatibleTest.java
- schema-registry/rest-service/src/test/java/com/hortonworks/registries/schemaregistry/avro/ConfluentRegistryCompatibleResourceTest.java
In Avro 1.8.2 APIs that exposes Jackson classes were deprecated. In the PR https://github.com/hortonworks/registry/pull/547, we moved away from these deprecated APIs to the recommended ones. The PR was then tested against Avro 1.9.0 and but was merged to MASTER with Avro 1.8.2. This PR bumps Avro version from 1.8.2 to 1.9.1 (https://github.com/apache/avro/releases). As part of this update I have commented out confluent tests as confluent serdes still has a dependency on  1.8.2. Will uncomment the tests once confluent updates their dependencies.
> ISSUE 605: Bump up the Avro version to 1.9.1

- docker/images/kafka/Dockerfile
It appears http://redrockdigimark.com/apachemirror/kafka is no longer operational, and thus `docker build` for `apache-kafka:1.0.0` produces the following error message:
```
Step 6/12 : ADD http://redrockdigimark.com/apachemirror/kafka/${KAFKA_VERSION}/${FILE_NAME} /opt/
ADD failed: failed to GET http://redrockdigimark.com/apachemirror/kafka/1.0.0/kafka_2.12-1.0.0.tgz with status 500 Internal Server Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
info@redrockdigimark.com to inform them of the time this error occurred,
and the …
```
> Download Kafka from a different server

- schema-registry/serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/kafka/KafkaAvroSerializer.java
> ISSUE-637 : KafkaAvroSerializer fails when schema.compatibility is specified in client configuration

- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaResolver.java
- schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/avro/AvroCompositeSchemasTest.java
- schema-registry/common/src/test/resources/avro/composites/expected-unions-with-defaults.avsc
- schema-registry/common/src/test/resources/avro/composites/unions-with-defaults.avsc
> ISSUE-633 : Fix error when creating a schema with field that is nullable but with default value

- examples/schema-registry/avro/src/main/java/com/hortonworks/registries/schemaregistry/examples/avro/SampleSchemaRegistryClientApp.java
- schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/ConfigEntry.java
- schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/errors/ConfigTypeConversionException.java
During initialization property file is read into a Properties object and
validated against a predefined set of rules. However, it was implicitly
assumed, that property values can only String typed.
This fix adds the necessary conversion beside the already existing validation.
FIxes #629
> ISSUE-631 : Schema Registry numeric properties cannot be set via a property file

- registry-dist/pom.xml
- registry-dist/src/main/assembly/binary.xml
This functionality is tied to `with-mysql-jar` profile
> MINOR: possibility to include mysql-connector jar in final tar.gz

- bootstrap/bootstrap-storage.sh
I've modified last time to use double brackets but it is better to use single one in case sh is the shell which executes the script
> MINOR: sh compatible conditions

- cache/src/main/java/com/hortonworks/registries/cache/view/io/loader/CacheLoaderAsync.java
- common/pom.xml
- pom.xml
- schema-registry/authorizer/authorization-agent/pom.xml
- schema-registry/authorizer/authorizer-core/pom.xml
- schema-registry/authorizer/ranger-plugin/ranger-authorizer-shim/pom.xml
- schema-registry/authorizer/ranger-plugin/ranger-authorizer/pom.xml
- schema-registry/rest-service/pom.xml
- webservice/pom.xml
Upgrade to Curator 4.2.0 and Upgrade to Guava 28.1
Fixes #687
> ISSUE-687 : Upgrade to Curator 4.2.0 and Upgrade to Guava 28.1

- conf/registry-dev-ssl.yaml
- conf/registry-dev.yaml
- conf/registry-inmemory-example.yaml
- conf/registry-mysql-example.yaml
- conf/registry-oracle-example.yaml
- conf/registry-oracle-ssl-example.yaml
- conf/registry-postgres-example.yaml
- conf/registry.yaml
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/DefaultSchemaRegistry.java
- schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/HAServerNotificationManager.java
- schema-registry/rest-service/src/test/resources/one-way-ssl-schema-registry.yaml
- schema-registry/rest-service/src/test/resources/schema-registry-ha.yaml
- schema-registry/rest-service/src/test/resources/schema-registry.yaml
- schema-registry/rest-service/src/test/resources/ssl-schema-registry-ha.yaml
- schema-registry/rest-service/src/test/resources/ssl-schema-registry.yaml
- webservice/src/main/java/com/hortonworks/registries/webservice/RegistryApplication.java
> ISSUE-690: Allow users to disble server side caching

- common-auth/pom.xml
- pom.xml
- tested with mvn clean install
- checked the difference in dependencies, no new libraries are pulled in
- the difference is only in the version of com.nimbusds:nimbus-jose-jwt:4.41.1 -> 7.9
> CDPD-10503 Upgrade nimbus-jose-jwt dependency in Schema Registry to mitigate CVEs

- webservice/pom.xml
The Schema registry installation package does not contain aws/azure HDFS dependencies any longer. 
When I simplified the dependencies in https://github.com/hortonworks/registry/commit/510185d7dbf314dfa9d365ca7020f791a4f4e51b, I removed the HDFS aws/azure dependencies in the `registry-common` dependent modules. I did this with the assumption that these and any newer HDFS dependent storages will be added in `registry-dist` pom.xml. Unfortunately,  I realised `registry-dist` does not package `registry-common` directly(https://github.com/hortonworks/registry/blob/master/registry-dist/pom.xml). It comes as a transitive dependency into installer package.
There are 2 ways to fix this:
1. Add `registry-common` as a direct dependency in `registry-dist` so that the installation package contains …
> Minor: HDFS dependencies for aws/azure file storage are missed out.

- README.md
- dependencies.gradle
- dev-tools/travis/travis-script.sh
- gradle.properties
We are moving all changes from Cloudera's internal repo to the public github repo. Also setting version to 1.0.0
> ISSUE-757: Move internal changes to the public repo

- schema-registry/schema-registry-common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaResolver.java
- schema-registry/schema-registry-common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaResolver.java
- schema-registry/schema-registry-common/src/main/java/com/hortonworks/registries/schemaregistry/json/JsonSchemaResolver.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serde/AbstractSnapshotDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/AvroSnapshotDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/avro/MessageAndMetadataAvroDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/json/AbstractJsonSnapshotDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/json/JsonSnapshotDeserializer.java
- schema-registry/schema-registry-serdes/src/main/java/com/hortonworks/registries/schemaregistry/serdes/json/MessageAndMetadataJsonDeserializer.java
- schema-registry/schema-registry-serdes/src/test/java/com/hortonworks/registries/schemaregistry/avro/serdes/MessageContextBasedAvroDeserializer.java
- schema-registry/schema-registry-serdes/src/test/java/com/hortonworks/registries/schemaregistry/serde/AbstractSnapshotDeserializerTest.java
- schema-registry/schema-registry-serdes/src/test/java/com/hortonworks/registries/schemaregistry/serdes/avro/AbstractAvroSnapshotDeserializerTest.java
- schema-registry/schema-registry-serdes/src/test/java/com/hortonworks/registries/schemaregistry/serdes/avro/kafka/KafkaAvroDeserializerTest.java
- schema-registry/schema-registry-serdes/src/test/java/com/hortonworks/registries/schemaregistry/serdes/json/JsonSnapshotDeserializerTest.java
Refactor the serdes code so it allows deserializing even when the topic and schema name doesn’t match. A major and long standing annoyance with our Deserializer.
> ISSUE-774 Support deserialization when the topic and schema names don't match
